modLoader="javafml"
loaderVersion="[47,48)"
license="All Rights Reserved"

[[mods]]
modId="autumnfoliage"
version="1.0.1"
displayName="Autumn Foliage"
displayTest="IGNORE_ALL_VERSION"
description='''
Client-side autumn vegetation rendering with broad vanilla/mod compatibility, smooth coordinate zones, Distant Horizons LOD recoloring, a purpose-built in-game settings UI, and optional server policy with selective client overrides.
'''

[[dependencies.autumnfoliage]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"

[[dependencies.autumnfoliage]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.autumnfoliage]]
modId="distanthorizons"
mandatory=false
versionRange="[3.3.0,)"
ordering="NONE"
side="CLIENT"
